### ISSUE TITLE
...

### ISSUE THREAD

**Issue by vitosotdihaet** [dodokek/Derivative-Calculator#1]
# I don't understand shit
### This makefile shat a lot in my terminal and after that refused to work
![image](https://user-images.githubusercontent.com/67521698/202909795-ce35f5e5-cb34-4fec-9f29-19e38699c5fc.png)
### But there is no instruction, so i thought it will work out of the box. However that was not the case.
# Please fix!

**Comment by dodokek** [comment]
Why don't you wait till the final ver of program instead of making me sad :( :( 👎

**Comment by vitosotdihaet** [comment]
Am wery sorry but there were no information presented about this project being work in progress !!! 😔

**Comment by dodokek** [comment]
Oh, yeah dude my bad now you know so ne pishi suda bolshe

**Comment by dodokek** [comment]
Добавил ридмишку специально для тебя, пупсик

**Comment by vitosotdihaet** [comment]
брат спасибо брат.
